### PR TITLE
[PR] Selection interface

### PR DESCRIPTION
**Pull request by philcable**
Initial work on #16.

### CODE REVIEW

**Comment by philcable** [comment]
@jeremyfelt Would you mind doing a preliminary #review of this? No rush at all - I just started experimenting and ended up at a point where it makes sense to be sure this is even the direction we want to go before putting more effort into it. Thanks!

**Comment by philcable** [comment]
Aside from the fact that we might want to host our own copy of the Select2 library, I think this might be ready...

**Comment by jeremyfelt** [comment]
@philcable I made 2 more changes:

* 5a544fd enqueues Select2 just a bit earlier. This sets things up so that Shortcode UI will use our version of Select2 rather than the version included in that plugin, which is probably better for us defensively.
* cda60b6 brings the library into the plugin rather than using the CDN version

If you're cool with both of those, then we're good! #reviewmerge?

**Comment by philcable** [comment]
👍  Looks great!

**Pull request merged**
